### PR TITLE
Missing translations, wrong domain; fixes #1834

### LINKED ISSUE #1834: [9.1+1.1] No translation of words
`.../glpi/front/computer.form.php`

Item "Software licenses"
glpi - assoc - computer form php

Item "FusInv Agent"
glpi - fusinv - computer form php

Item "FusInv Agent"
glpi - fusinv agent - computer form php

`...glpi/front/crontask.form.php`
glpi - cleanoldagents - google chrome

glpi - computer - google chrome 2016-06-07 15 56 50

`...glpi/front/task.form.php`
glpi - fusioninventory - task form php

`...glpi/front/profile.form.php`
item "fusioninventory"
glpi - profile form php 2016-06-21 13 34 59

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

**Comment by trasher** [comment]
I've not been able to find `FusInv Agent` and `running task {xyz}`

File: install/install.php [hunk 1]
```diff
@@ -314,10 +314,10 @@ function pluginFusioninventoryInstall($version, $migrationname='Migration') {
                          array('mode'=>2, 'allowmode'=>3, 'logs_lifetime'=>30));
       CronTask::Register('PluginFusioninventoryAgent', 'cleanoldagents', (3600 * 24),
                          array('mode' => 2, 'allowmode' => 3, 'logs_lifetime' => 30,
-                               'comment'=>'Clean agents not contacted since xxx days'));
+                               'comment'=> __('Clean agents not contacted since xxx days', 'fusioninventory')));
```
Comment (wawax) [inline install/install.php]: I suppose that it's better to rename the string in "Delete agent that have not contacted the server since xxx days".
